<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
Auth::requireAdmin();
$db = Database::getInstance();
$roleStats = $db->getAll('SELECT role, COUNT(*) AS total FROM users GROUP BY role ORDER BY role');
$courseStats = $db->getAll("SELECT c.title, c.status, COUNT(e.id) AS enrollments, SUM(e.status = 'completed') AS completions, AVG(e.progress) AS average_progress FROM courses c LEFT JOIN enrollments e ON e.course_id = c.id GROUP BY c.id ORDER BY enrollments DESC, c.title");
$monthly = $db->getAll("SELECT DATE_FORMAT(created_at, '%Y-%m') AS month, COUNT(*) AS users FROM users GROUP BY month ORDER BY month DESC LIMIT 12");
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Analytics | ICTECH</title><link rel="stylesheet" href="../assets/css/style.css?v=20260902"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><main class="container py-5"><header class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-5"><div><p class="text-secondary mb-1">ADMIN ANALYTICS</p><h1>Platform Performance</h1><p class="text-muted mb-0">A clear view of users, course demand, and learning outcomes.</p></div><a href="index.php" class="btn btn-outline-primary">Back to Dashboard</a></header><div class="row g-4"><div class="col-lg-5"><section class="card h-100"><div class="card-body"><h2 class="h4">Users by Role</h2><div class="analytics-list"><?php foreach ($roleStats as $stat): ?><div class="analytics-row"><span class="text-capitalize"><?php echo h($stat['role']); ?></span><strong><?php echo (int) $stat['total']; ?></strong></div><?php endforeach; ?></div></div></section></div><div class="col-lg-7"><section class="card h-100"><div class="card-body"><h2 class="h4">Recent User Growth</h2><div class="analytics-list"><?php foreach ($monthly as $stat): ?><div class="analytics-row"><span><?php echo h($stat['month']); ?></span><strong><?php echo (int) $stat['users']; ?></strong></div><?php endforeach; ?><?php if (!$monthly): ?><p class="text-muted mb-0">No user activity recorded yet.</p><?php endif; ?></div></div></section></div><div class="col-12"><section class="card"><div class="card-body"><h2 class="h4">Course Performance</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Course</th><th>Status</th><th>Enrollments</th><th>Completions</th><th>Average Progress</th></tr></thead><tbody><?php foreach ($courseStats as $stat): ?><tr><td><?php echo h($stat['title']); ?></td><td><?php echo h($stat['status']); ?></td><td><?php echo (int) $stat['enrollments']; ?></td><td><?php echo (int) $stat['completions']; ?></td><td><?php echo $stat['average_progress'] !== null ? number_format((float) $stat['average_progress'], 1) . '%' : '0%'; ?></td></tr><?php endforeach; ?></tbody></table></div></div></section></div></div></main></body></html>
